// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivqgmbhadlqgsilekknv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cWdtYmhhZGxxZ3NpbGVra252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDk2MzgsImV4cCI6MjA3Mzg4NTYzOH0.9WLOP9fJWT3JYkuUANx4q1n9srL_6GrUknVsCc6PLUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});